### ISSUE TITLE
Upgrade should overwrite existing installation

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Tatin#111]
The upgrade suggestion is a nice feature, I think it needs to replace exiting files

```
You are using an outdated version of the Tatin client.
Would you like to update automatically? (Y/n) Y

You version of Tatin is 0.80.0+1285
Latest published version is 0.81.0
Would you like to download and install 0.81.0 ? (y/n) y
* Command Execution Failed: FILE NAME ERROR: C:/Users/rpark/Documents/MyUCMDs/Tatin/Assets/Runtime/Rumba/mime.csv: Already exists
```

**Comment by aplteam** [comment]
What Tatin attempts is to remove the folder upfront, but by accident I did not check the return code which can be non-zero if for example somebody is looking into the folder with Windows Explorer.

Something like this must have happened here. 

Removing the folder upfront is the right thing to do because this way getting rid of files that have become superfluous is easy.
