### ISSUE TITLE
LoadDependencies failure even with v0.50.2

### ISSUE THREAD

**Issue by DavinChurch** [aplteam/Tatin#59]
I believe I reported this problem under v0.50.1 but it is still occurring for me:

```
      ]tatin.init
User settings re-established in ⎕SE._Tatin.Client from D:\Users\Davin\AppData\Roaming\Tatin\tatin-client.json
      ]tatin.version
 Tatin  0.50.2+706  2021-09-12 
      ]tatin.loaddependencies D:/Dyalog/Packages #
* Command Execution Failed: VALUE ERROR

```

**Comment by aplteam** [comment]
This a different problem. It is caused by `⎕SE.Dyalog.Array` not being around. 

Tatin requires Link 3.0.0, and that version comes with `⎕SE.Dyalog.Array`. 

The next version of Tatin will provide a proper error message rather than just a "VALUE ERROR", and it will also check whether the requirements are met and report it if not.
