### ISSUE TITLE
Install package prints long vertical text to session

### ISSUE THREAD

**Issue by rikedyp** [aplteam/Tatin#83]
```APL
      ]tatin.version
 Tatin  0.61.1+887  2022-01-03 
```

```APL
      ]installPackage MarkAPL /d/blog/Jup2Blog
Scanning 1 registry for MarkAPL...
   found in https://tatin.dev/
  Attempting to install https://tatin.dev/aplteam-MarkAPL-11.0.2...
  Establish dependencies...
  4 dependencies identified
  Fetching from https://tatin.dev/...
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_152509834.zip...
  Add aplteam-MarkAPL-11.0.2 to dependency file...
  Fetching from https://tatin.dev/...
Link Warning: ⎕SE.Link.Notify: created C:/d/blog/jup2blog/aplteam-MarkAPL-11.0.2: invalid name defined by file: C:/d/blog/
      jup2blog/aplteam-MarkAPL-11.0.2
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_152510481.zip...
  Fetching from https://tatin.dev/...
Link Warning: ⎕SE.Link.Notify: created C:/d/blog/jup2blog/aplteam-APLTreeUtils2-1.1.1: invalid name defined by file: C:/d/
      blog/jup2blog/aplteam-APLTreeUtils2-1.1.1
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_152510969.zip...
  Fetching from https://tatin.dev/...
Link Warning: ⎕SE.Link.Notify: created C:/d/blog/jup2blog/aplteam-FilesAndDirs-5.0.1: invalid name defined by file: C:/d/b
      log/jup2blog/aplteam-FilesAndDirs-5.0.1
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_152511460.zip...
  Saving build list... 
a
p
l
t
e
a
m
-
M
a
r
k
A
P
L
-
1
1
.
0
.
2
```

**Comment by aplteam** [comment]
I struggle to understand why you get
```
Link Warning: ⎕SE.Link.Notify: created C:/d/blog/jup2blog/aplteam-MarkAPL-11.0.2: invalid name defined by file: C:/d/blog/
      jup2blog/aplteam-MarkAPL-11.0.2
```

It appears that your current drive is C:, and that C:\d\blog\jup2blog are all directories that exist, so why do you get that warning? What am I missing?

**Comment by aplteam** [comment]
It's a directory into which the package is installed.

**Comment by mkromberg** [comment]
OK, so I suspect that the problem is that if a directory is created within a currently linked & watched directory, and the directory has a name that cannot be used to create a namespace, Link considers it worth warning you about. I think this is a mistake, given that we do not warn of this if such a directory exists when the link is created. I have logged https://github.com/Dyalog/link/issues/459.

Having said that, I would like to warn that it is a questionable practice to be actively watching directories that your own code is making significant changes to. I would suggest creating the folders and then (re-)linking at the end, to avoid potential "thrashing" on file system watchers. FSW's are OK to monitor file edits etc, but are not a reliable communication protocol for high speed / high frequency updates. If the APL interpreter is busy with something and does not process FSW events fast enough, the OS will discard the events to protect itself, rather than maintain a large queue.

**Comment by rikedyp** [comment]
Well it still happened to me even in a complete CLEAR WS. As a last resort I'm going to try and remove all traces of Tatin, possibly re-install Dyalog, and try again.

```
      ]InstallPackage MarkAPL ./packages
The install folder does not yet exist; create? (Y/n) Y
Scanning 1 registry for MarkAPL...
   found in https://tatin.dev/
  Attempting to install https://tatin.dev/aplteam-MarkAPL-11.0.2...
  Establish dependencies...
  4 dependencies identified
  Fetching from https://tatin.dev/...
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_8194184.zip...
  Add aplteam-MarkAPL-11.0.2 to dependency file...
  Fetching from https://tatin.dev/...
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_81941785.zip...
  Fetching from https://tatin.dev/...
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_81942264.zip...
  Fetching from https://tatin.dev/...
  Unzipping C:\Users\rpark\AppData\Local\Temp\rpark_81942747.zip...
  Saving build list... 
a
p
l
t
e
a
m
-
M
a
r
k
A
P
L
-
1
1
.
0
.
2
```

**Comment by rikedyp** [comment]
I deleted all traces of Tatin and installed the client again and cannot reproduce. Closing.
